import type {
  Skill,
  Stats,
  ScanResult,
  FilterOptions,
  FilterOptionWithCount,
  SkillQuery,
  SearchHistoryItem,
  Tag,
} from "@/store/skillStore";
import type { AppSettings } from "@/store/settingsStore";

/**
 * Web data layer. Replaces the Tauri IPC bridge in the browser build.
 *
 * The catalogue is a committed static JSON file plus one Markdown file per
 * Skill (`public/catalog/`), generated by `scripts/generate-catalog.mjs`. The
 * Web MVP is strictly read-only: it never touches the local filesystem, never
 * asks for an API key, and never executes a process.
 */

const CATALOG_URL = `${import.meta.env.BASE_URL}catalog/index.json`;
const SKILLS_DIR = `${import.meta.env.BASE_URL}catalog/skills`;

// ── Local persistence keys (browser only) ────────────────────────────────
const FAVORITES_KEY = "skillhub_web_favorites";
const RECENT_KEY = "skillhub_web_recent_views";
const HISTORY_KEY = "skillhub_web_search_history";
const SETTINGS_KEY = "skillhub_web_settings";

function readJson<T>(key: string, fallback: T): T {
  try {
    const raw = localStorage.getItem(key);
    return raw ? (JSON.parse(raw) as T) : fallback;
  } catch {
    return fallback;
  }
}

function writeJson(key: string, value: unknown): void {
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch {
    // Storage may be unavailable (private mode / quotas). Browsing still works.
  }
}

// ── Catalogue loading ──────────────────────────────────────────────────────

let catalogPromise: Promise<Skill[]> | null = null;

async function catalog(): Promise<Skill[]> {
  if (localOverride) return localOverride;
  if (!catalogPromise) {
    catalogPromise = fetch(CATALOG_URL)
      .then((res) => {
        if (!res.ok) throw new Error(`Catalogue unavailable (${res.status})`);
        return res.json();
      })
      .then((data: { skills: Skill[] }) => data.skills);
  }
  return catalogPromise;
}

const contentCache = new Map<string, string>();

async function skillContent(id: string): Promise<string | null> {
  if (id in localContents) return localContents[id];
  const cached = contentCache.get(id);
  if (cached !== undefined) return cached;
  const res = await fetch(`${SKILLS_DIR}/${encodeURIComponent(id)}.md`);
  if (!res.ok) {
    contentCache.set(id, "");
    return "";
  }
  const text = await res.text();
  contentCache.set(id, text);
  return text;
}

// ── Locally loaded skills (opt-in, browser-only, nothing uploaded) ────────

let localOverride: Skill[] | null = null;
let localContents: Record<string, string> = {};

/** Replace the static catalogue with skills the user picked from a local folder. */
export function setLocalSkills(
  skills: Skill[] | null,
  contents: Record<string, string> = {},
): void {
  localOverride = skills;
  localContents = contents;
  contentCache.clear();
}

export function hasLocalSkills(): boolean {
  return localOverride !== null;
}

// ── Favorites ──────────────────────────────────────────────────────────────

function favoriteIds(): string[] {
  return readJson<string[]>(FAVORITES_KEY, []);
}

function withFavorites(skills: Skill[]): Skill[] {
  const fav = new Set(favoriteIds());
  return skills.map((s) => ({ ...s, favorite: fav.has(s.id) }));
}

// ── Recent views ───────────────────────────────────────────────────────────

interface RecentEntry { id: string; viewed_at: number }

function recentEntries(): RecentEntry[] {
  return readJson<RecentEntry[]>(RECENT_KEY, []);
}

function recordRecentView(id: string): void {
  const entries = recentEntries().filter((e) => e.id !== id);
  entries.unshift({ id, viewed_at: Date.now() });
  writeJson(RECENT_KEY, entries.slice(0, 30));
}

// ── Search history ─────────────────────────────────────────────────────────

function historyEntries(): SearchHistoryItem[] {
  return readJson<SearchHistoryItem[]>(HISTORY_KEY, []);
}

function recordHistory(query: string): void {
  const q = query.trim();
  if (!q) return;
  const entries = historyEntries().filter((e) => e.query !== q);
  entries.unshift({ id: Date.now(), query: q, created_at: new Date().toISOString() });
  writeJson(HISTORY_KEY, entries.slice(0, 50));
}

// ── Settings ───────────────────────────────────────────────────────────────

const DEFAULT_WEB_SETTINGS: AppSettings = {
  api_key: "",
  language: "en",
  theme_mode: "system",
  custom_primary: "#6366f1",
  custom_background: "#0f0f0f",
  minimize_to_tray: false,
  skill_directory: null,
};

function loadWebSettings(): AppSettings {
  const stored = readJson<Partial<AppSettings>>(SETTINGS_KEY, {});
  const language = stored.language === "zh" ? "zh" : "en";
  const theme_mode =
    stored.theme_mode === "light" ||
    stored.theme_mode === "dark" ||
    stored.theme_mode === "custom"
      ? stored.theme_mode
      : "system";
  return {
    ...DEFAULT_WEB_SETTINGS,
    ...stored,
    api_key: "",
    language,
    theme_mode,
    minimize_to_tray: false,
    skill_directory: null,
  };
}

function saveWebSettings(settings: AppSettings): AppSettings {
  // Never persist secrets or desktop-only paths on the Web build.
  const sanitized: AppSettings = {
    ...settings,
    api_key: "",
    minimize_to_tray: false,
    skill_directory: null,
  };
  writeJson(SETTINGS_KEY, sanitized);
  return sanitized;
}

// ── Query / filter / sort ──────────────────────────────────────────────────

function applyQuery(skills: Skill[], q: SkillQuery): Skill[] {
  let out = skills;

  const search = q.search?.trim().toLowerCase();
  if (search) {
    const terms = search.split(/\s+/).filter(Boolean);
    out = out.filter((s) => {
      const hay = `${s.name} ${s.description}`.toLowerCase();
      return terms.every((term) => hay.includes(term));
    });
  }

  if (q.category) {
    const c = q.category.toLowerCase();
    out = out.filter((s) => (s.category ?? "").toLowerCase() === c);
  }
  if (q.risk) {
    const r = q.risk.toLowerCase();
    out = out.filter((s) => (s.risk ?? "").toLowerCase() === r);
  }
  if (q.source) {
    const src = q.source.toLowerCase();
    out = out.filter((s) => (s.source ?? "").toLowerCase() === src);
  }
  if (q.favorite_only) {
    const fav = new Set(favoriteIds());
    out = out.filter((s) => fav.has(s.id));
  }
  if (q.tag_ids && q.tag_ids.length > 0) {
    // The static Web catalogue has no tag system; matching none is correct.
    out = [];
  }

  if (q.sort_field) {
    const dir = q.sort_direction === "Desc" ? -1 : 1;
    out = [...out].sort((a, b) => {
      const av = sortValue(a, q.sort_field!);
      const bv = sortValue(b, q.sort_field!);
      return av.localeCompare(bv) * dir;
    });
  }

  return out;
}

function sortValue(skill: Skill, field: string): string {
  switch (field) {
    case "Name":
      return skill.name;
    case "DateAdded":
      return skill.date_added ?? "";
    case "Category":
      return skill.category ?? "";
    case "Risk":
      return skill.risk ?? "";
    case "Source":
      return skill.source ?? "";
    default:
      return skill.name;
  }
}

function computeStats(skills: Skill[]): Stats {
  const total = skills.length;
  let categorized = 0;
  const catMap = new Map<string, number>();
  const riskMap = new Map<string, number>();
  for (const s of skills) {
    const hasCategory = !!s.category && s.category.trim() !== "";
    if (hasCategory) categorized += 1;
    const cat = hasCategory ? s.category! : "(uncategorized)";
    catMap.set(cat, (catMap.get(cat) ?? 0) + 1);
    if (s.risk && s.risk.trim() !== "") {
      riskMap.set(s.risk, (riskMap.get(s.risk) ?? 0) + 1);
    }
  }
  const category_counts = [...catMap.entries()]
    .map(([category, count]) => ({ category, count }))
    .sort((a, b) => b.count - a.count);
  const risk_counts = [...riskMap.entries()]
    .map(([risk, count]) => ({ risk, count }))
    .sort((a, b) => b.count - a.count);
  return {
    total_count: total,
    categorized_count: categorized,
    uncategorized_count: total - categorized,
    category_counts,
    risk_counts,
  };
}

function computeFilters(skills: Skill[]): FilterOptions {
  const categories = new Map<string, number>();
  const risks = new Map<string, number>();
  const sources = new Map<string, number>();
  for (const s of skills) {
    if (s.category && s.category.trim()) {
      categories.set(s.category, (categories.get(s.category) ?? 0) + 1);
    }
    if (s.risk && s.risk.trim()) {
      risks.set(s.risk, (risks.get(s.risk) ?? 0) + 1);
    }
    if (s.source && s.source.trim()) {
      sources.set(s.source, (sources.get(s.source) ?? 0) + 1);
    }
  }
  const toOptions = (map: Map<string, number>): FilterOptionWithCount[] =>
    [...map.entries()]
      .map(([value, count]) => ({ value, count }))
      .sort((a, b) => a.value.localeCompare(b.value));
  return {
    categories: toOptions(categories),
    risks: toOptions(risks),
    sources: toOptions(sources),
  };
}

function matchSkills(query: string, limit: number, skills: Skill[]): Skill[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return skills
    .filter(
      (s) =>
        s.name.toLowerCase().includes(q) || s.description.toLowerCase().includes(q),
    )
    .slice(0, limit);
}

// ── Command dispatcher ─────────────────────────────────────────────────────

export async function webInvoke<T>(
  command: string,
  args: Record<string, unknown> = {},
): Promise<T> {
  switch (command) {
    case "get_all_skills": {
      return withFavorites(await catalog()) as T;
    }
    case "get_skill_by_id": {
      const id = String(args.id ?? "");
      const skills = await catalog();
      const skill = skills.find((s) => s.id === id) ?? null;
      return (skill ? withFavorites([skill])[0] : null) as T;
    }
    case "get_skill_content": {
      const id = String(args.id ?? "");
      const skills = await catalog();
      const skill = skills.find((s) => s.id === id);
      if (!skill) return null as T;
      const content = await skillContent(id);
      return { id: skill.id, name: skill.name, content } as T;
    }
    case "search_skills": {
      const query = String(args.query ?? "");
      const skills = await catalog();
      return withFavorites(matchSkills(query, 100, skills)) as T;
    }
    case "query_skills": {
      const query = (args.query ?? {}) as SkillQuery;
      const skills = await catalog();
      const filtered = applyQuery(skills, query);
      const offset = Number(query.offset ?? 0);
      const limit = Number(query.limit ?? filtered.length);
      const page = filtered.slice(offset, offset + limit);
      return { skills: withFavorites(page), total_count: filtered.length } as T;
    }
    case "get_filters": {
      return computeFilters(await catalog()) as T;
    }
    case "get_stats": {
      return computeStats(await catalog()) as T;
    }
    case "scan_skills": {
      // The Web build has no local scanner by design.
      return { skills: [], errors: [] } as ScanResult as T;
    }
    case "get_favorites_count": {
      return favoriteIds().length as T;
    }
    case "toggle_favorite": {
      const request = args.request as { skill_id: string; favorite: boolean };
      const ids = new Set(favoriteIds());
      if (request?.favorite) ids.add(request.skill_id);
      else ids.delete(request?.skill_id);
      writeJson(FAVORITES_KEY, [...ids]);
      return undefined as T;
    }
    case "get_recent_views": {
      const limit = Number(args.limit ?? 30);
      const skills = await catalog();
      const byId = new Map(skills.map((s) => [s.id, s]));
      const views = recentEntries()
        .map((e) => byId.get(e.id))
        .filter((s): s is Skill => !!s)
        .slice(0, limit);
      return withFavorites(views) as T;
    }
    case "add_recent_view": {
      recordRecentView(String(args.skillId ?? ""));
      return undefined as T;
    }
    case "get_search_history": {
      const limit = Number(args.limit ?? 10);
      return historyEntries().slice(0, limit) as T;
    }
    case "add_search_history": {
      recordHistory(String(args.query ?? ""));
      return undefined as T;
    }
    case "clear_search_history": {
      writeJson(HISTORY_KEY, []);
      return undefined as T;
    }
    case "search_suggestions": {
      const query = String(args.query ?? "");
      const limit = Number(args.limit ?? 8);
      const skills = await catalog();
      return withFavorites(matchSkills(query, limit, skills)) as T;
    }
    case "get_all_tags":
      return [] as Tag[] as T;
    case "get_skill_tags":
      return [] as Tag[] as T;
    case "create_tag":
    case "delete_tag":
    case "assign_tag":
    case "remove_tag":
      return undefined as T;
    case "get_conflict_count":
      return 0 as T;
    case "get_categorization_conflicts":
      return [] as T;
    case "resolve_conflicts":
      return undefined as T;
    case "get_categorization_history":
      return [] as T;
    case "get_skill_ids_by_query": {
      const query = (args.query ?? {}) as SkillQuery;
      const skills = await catalog();
      return applyQuery(skills, query).map((s) => s.id) as T;
    }
    case "load_settings":
      return loadWebSettings() as T;
    case "save_settings":
      return saveWebSettings(args.settings as AppSettings) as T;
    case "get_locale":
      return (navigator.language?.toLowerCase().startsWith("zh") ? "zh" : "en") as T;
    case "get_environment_diagnostics":
      return [] as T;
    case "get_categorize_progress":
      return { total: 0, processed: 0, succeeded: 0, failed: 0, current_skill: null, running: false } as T;
    default:
      // Execution, scanning, AI categorization, import/export, backup and
      // updater commands are desktop-only and are never reachable from the
      // Web UI. Fail loudly so a future regression is caught immediately.
      throw new Error(`"${command}" is not available in the SkillHub web version.`);
  }
}
